/*
 Generated by typeshare 1.13.4
*/

/** A key as shown in the admin panel (never includes the secret). */
export interface ApiKey {
	id: string;
	name: string;
	role: string;
	created_at: string;
	expires_at?: string;
	last_used_at?: string;
}

export interface CreateRequest {
	name: string;
	role: string;
	expires_at?: string;
}

export interface CreateResponse {
	id: string;
	name: string;
	token: string;
}

export interface HelloResponse {
	message: string;
}

export interface UserInfo {
	email?: string;
	username?: string;
	role: string;
}

